### ISSUE TITLE
Upgrade images for Jakarta EE

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jakartaee-tutorial#183]
Lots of images refer to Java EE technologies and need to be updated.

@bshannon can Oracle donate the PSDs for the images? If that's not feasible we may need to ask some designer to create new pictures.

**Comment by bshannon** [comment]
I think the original images were created in FrameMaker.

**Comment by ggam** [comment]
I don't know FrameMarker but I suppose that means things are more complicated.

Current images look a bit old and would be better redesigned from scratch, but in the meantime, can Oracle donate a version of the images with the texts modified?

**Comment by keilw** [comment]
@ggam @bshannon What is the status here? We're talking about only a handful of the 69 images, leaving aside `jakartaeett_dt_007-jakartaeett_dt_009` that are completely outdated anyway because they still say "New in Java EE 7" and therefore lack any changes in Java EE 8 or Jakarta EE 8, and ignoring phrases like "JMS" or "EJB" for now, if you simply replace the term "Java" with "Jakarta" it may be down to around a dozen images max. I had to fix one for a Tutorial I am currently working on myself
![jakartaeett_dt_056 (Custom2)](https://user-images.githubusercontent.com/70496/73317550-c476ab00-4236-11ea-8578-6ea9b077b73e.png)
The font may not look perfect, but it's better than nothing. So if no PSD or better Gimp format was available soon, maybe that's the only way to at least get it out for Jakarta EE 8 before 9 is supposed to ship?

**Comment by bshannon** [comment]
What you see is what we have.  It would be great to get all the images updated
and replaced with something more maintainable.  Ideally, all the updated images
would have the same look and feel.

**Comment by cpusam** [comment]
@ggam Just a little question: the images contains icons that appears over all images, so, does it needs be the same icon design, or needs changes completely the icons' images and choose others more modern?
If just need redo the icons used in the images, it will need just remade them in svg and so, use them in the images.
For example, the computer icon it's very used in many images, if remade it to svg then will be easier to remake the others relatives images.
I will try to do some icon and see what time will take for to do it.

**Comment by ggam** [comment]
Hi @cpusam. Would be awesome if we could get more modern versions of the icons, but having the same images converted to SVG is enough to edit the texts.

Anything you do will be welcomed!

**Comment by gabrielbussolo** [comment]
Hey guys, I'm not a designer but I did this image for eclipse-ee4j/jakartaee-firstcup#17 I can do the same for jakarta-tutorial

**Comment by ggam** [comment]
Done
